### ISSUE TITLE
No detection result when using MobileNetYOLO

### ISSUE THREAD

**Issue by imistyrain** [eric612/YoloV2-MobileNet-NCS#2]
I try to convert MobileNetYOLO and got the graph, but when run tests it outputs nothing. Is there any thing wrong?

**Comment by eric612** [comment]
1. I did not maintenance this project a long time , and the mobilenet yolo model in this project was training form old caffe which mAP was bad.  You can try the new model from https://github.com/eric612/MobileNet-YOLO 

2. shrink = (cv2.resize(img, size, interpolation=cv2.INTER_AREA)/255.0) here need to modify
   tiny yolo mean value was 0 and scale was 1/255.0
   mobilenet yolo mean value was 127.5 (or 0.5)  and scale was 1/127.5

**Comment by imistyrain** [comment]
Thank you for your quick response. I will check the code.
